### PR TITLE
Freshly imported to Android Studio.

### PR DESCRIPTION
**Pull request by DaveMelcher**
Compiles and runs with Enabler 6.06

### CODE REVIEW

**Comment by peplin** [comment]
Nice! I think the `.gradle` and all `build` directories that have generated files should be in the `.gitignore` so they aren't tracked.

**Comment by DaveMelcher** [comment]
Ah!  Thanks!  I figured I missed something like that.

**Comment by peplin** [comment]
The PR is updated automatically, always pointing to the latest commit in the branch. You might want to re-do the original commit so it doesn't have all of the generated files (otherwise those will be tracked forever until they are explicitly `git rm -r`'d). Something like this: https://github.com/openxc/shiftknob-android/commit/85e2d8ae5d4f7c0782fc839f2ab6c229d7c654db

In that branch I also ignored the `*.iml` files from Android Studio since they are local development environment specific.

One thought - is there a way to not distribute FTDriver as a part of this repo?  If not, we probably have to include more of the project like the README and license information. Either way, the README has to be updatd with new build instructions.

**Comment by DaveMelcher** [comment]
Hrm.  I've already pushed the .gitignore change commit after the commit that added the generated files.  Also, the commit adding the unnecessary files was the first of the branch.  Do I git reset to master?  And is that going to clobber my local changes?

As for FTDriver, that's something else I missed.  I believe we can just add that to the .gitignore as well, and have people get their own copy, as before.

**Comment by peplin** [comment]
A `git reset origin/master` will reset the HEAD pointer back to master, but leave all of your changes on disk. From there, you could re-commit only the stuff you wanted to keep. Just watch out for `git reset --hard` which trashes anything on disk. Either way, the commits are still pushed to GitHub and on my machine so you wouldn't be totally out of luck. 

What I did to create that example commit was `git rebase -i origin/master`, the mark all of the commits in your branch as "squashed" to get them into one. Then I ran `git reset HEAD~1` to un-do the single commit, then re-added and committed only the stuff I wanted to keep. Now that the gitignore was in place, it was easier since the generated files were excluded automatically.

**Comment by DaveMelcher** [comment]
Hrm.  That doesn't look like it worked.  Is it expected that the original commit didn't disappear from the log?

From the most recent commit, I...
git rebase -i origin/master
git reset HEAD~1

Modified the .gitignore and readme.mkd, then
git commit -a
git push --force

**Comment by DaveMelcher** [comment]
I'm going to abandon this branch and put one together more cleanly.

**Pull request closed without merging**
